version: "2.3"
services:
  quiz:
    container_name: quiz
    restart: always
    cpu_count: 2
    mem_limit: 2048m
    mem_reservation: 1024m
    # this is used for local development of the container
    build:
      context: ./containers/quiz
      args:
        environment: local
    volumes:
      - ./containers/quiz/src:/var/www/quiz
    working_dir: /var/www/quiz
    links:
      - mysql:mysql
    ports:
      - 8001:8888
      - 2001:2222
  mysql:
    build:
      context: .
      dockerfile: build/mysql/Dockerfile
    container_name: mysql
    restart: always
    cpu_count: 2
    mem_limit: 2048m
    mem_reservation: 1024m
    volumes:
      - mysql-data-volume:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: quiz
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: docker
      MYSQL_PASSWORD: secret
volumes:
  mysql-data-volume:
